# data augmentation
dataset:
  common:
    NAME: IRRADIANCE
    data_root: D:\Master Thesis Data\IrradianceNet\dset100_xl_regular
    test_area: 5
    voxel_size: 0.04 #For irradiance
    split_ratio: 0.88889
    bins: 10
    compute_hist: False
  train:
    split: train
    voxel_max: 10000
    loop: 1 # here, the training has been looped 30 times. therefore, the training epochs do not need much.
    presample: True
    show: False
    _overwrite_dset_size: 0
  val:
    split: val
    voxel_max: 28000
    presample: True
    show: False
    _overwrite_dset_size: 0
  test:
    split: test
    voxel_max: null
    presample: True
    data_root: D:\Master Thesis Data\IrradianceNet\test_dset100_xl_regular
    shuffle: False

feature_keys: pos,normals
num_classes: 1
batch_size: 8
val_batch_size: 8
test_batch_size: 1

dataloader:
  num_workers: 0

datatransforms:
  train: [PointsToTensor, PointCloudCenterAndNormalize, IrradianceClipNormalize] 
  val: [PointsToTensor, PointCloudCenterAndNormalize, IrradianceClipNormalize]
  test: [PointsToTensor, PointCloudCenterAndNormalize, IrradianceClipNormalize]
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    scale: [0.9, 1.1]
    angle: [0, 0, 1]
    jitter_sigma: 0.005
    jitter_clip: 0.02
    centering: False
    normalize: True
    norm_min: -1 # Minimum value of normalization range for data values (either 0 or -1 or  null)
    irradiance_min: -1
    dmin: 0
    dmax: null


# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
val_fn: validate
ignore_index: null
epochs: 25
max_epoch: 26

cls_weighed_loss: False

criterion_args:
  NAME: MSELoss # ! CrossEntropy
  

# ! Added
regression: True

optimizer:
 NAME: 'adamw'  # performs 1 point better than adam
 weight_decay: 1.0e-4

# lr_scheduler:
sched: cosine
warmup_epochs: 0

# plateau scheduler:
#####
patience_epochs: 10
decay_rate: 0.1
#####

min_lr: 1.0e-5 #
lr: 0.01 # LR linear rule.

grad_norm_clip: 10
use_voting: False
# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
log_dir: 'IrradianceNet'
save_freq: -1 # save epoch every xxx epoch114s, -1 only save last and best. 
val_freq: 1

wandb:
  project: IrradianceNet
  sweep: False
  use_wandb: True
  id: null