
model:
  NAME: BaseSeg
  encoder_args:
    NAME: PointVectorEncoder
    blocks: [1, 4, 7, 4, 4] 
    strides: [1, 4, 4, 4, 4]
    sa_layers: 1
    sa_use_res: False 
    width: 64
    in_channels: 4
    expansion: 4
    radius: 0.1
    nsample: 32 
    flag: 1 #means s3dis
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: PointVectorDecoder
  cls_args:
    NAME: SegHead
    num_classes: 1
    in_channels: null
    norm_args:
      norm: 'bn'

batch_size: 32

# do not conduct rotation in small model.
datatransforms:
  train: [PointsToTensor, PointCloudCenterAndNormalize, IrradianceClipNormalize] 
  val: [PointsToTensor, PointCloudCenterAndNormalize, IrradianceClipNormalize] 
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    scale: [0.9, 1.1]
    jitter_sigma: 0.005
    jitter_clip: 0.02
